/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import gui.panels.ApplicantPanel;
import gui.panels.AttendancePanel;
import gui.panels.DepartmentPanel;
import gui.panels.EmployeePanel;
import gui.panels.HomePanel;
import gui.panels.LeavePanel;
import gui.panels.PositionPanel;
import gui.panels.SalaryPanel;
import gui.panels.ScheduelePanel;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.SwingUtilities;

/**
 *
 * @author senad
 */
public class Dashboard2 extends javax.swing.JFrame {

    private boolean isCollapsed = false;
    private final int EXPANDED_WIDTH = 200;
    private final int COLLAPSED_WIDTH = 95;
    private FlatSVGIcon collapseIcon;
    private FlatSVGIcon expandIcon;
    private FlatSVGIcon departmentIcon;
    private FlatSVGIcon homeIcon;
    private FlatSVGIcon positionIcon;
    private FlatSVGIcon logoutIcon;
    private FlatSVGIcon employeesIcon;
    private FlatSVGIcon applicantIcon;
    private FlatSVGIcon attendanceIcon;
    private FlatSVGIcon leaveIcon;
    private FlatSVGIcon schedueleIcon;
    private FlatSVGIcon salaryIcon;
    private FlatSVGIcon logoIcon;

    /**
     * Creates new form Test
     */
    public Dashboard2() {
        initComponents();
        InitialiseUi();
    }

    private void InitialiseUi() {
        setExtendedState(Dashboard2.MAXIMIZED_BOTH);
        collapseIcon = new FlatSVGIcon("resources//sidebar.svg", 30, 30);
        jButton8.setIcon(collapseIcon);
        homeIcon = new FlatSVGIcon("resources//home.svg", 30, 30);
        homeButton.setIcon(homeIcon);
        departmentIcon = new FlatSVGIcon("resources//sitemap.svg", 30, 30);
        departmentButton.setIcon(departmentIcon);
        positionIcon = new FlatSVGIcon("resources//briefcase.svg", 30, 30);
        positionButton.setIcon(positionIcon);
        employeesIcon = new FlatSVGIcon("resources//users.svg", 31, 28);
        employeeManagementButton.setIcon(employeesIcon);
        applicantIcon = new FlatSVGIcon("resources//user-plus.svg", 31, 28);
        applicantButton.setIcon(applicantIcon);
        attendanceIcon = new FlatSVGIcon("resources//calendar-check.svg", 30, 30);
        attendanceButton.setIcon(attendanceIcon);
        leaveIcon = new FlatSVGIcon("resources//calendar-times.svg", 30, 30);
        leaveManagementButton.setIcon(leaveIcon);
        schedueleIcon = new FlatSVGIcon("resources//clock.svg", 30, 30);
        schedueleButton.setIcon(schedueleIcon);
        salaryIcon = new FlatSVGIcon("resources//dollar-sign.svg", 30, 32);
        salaryButton.setIcon(salaryIcon);
        logoIcon = new FlatSVGIcon("resources//building.svg", 30, 35);
        logoLabel.setIcon(logoIcon);

        logoutIcon = new FlatSVGIcon("resources//logout.svg", 30, 30);
        logoutButton.setIcon(logoutIcon);

        logoutPanel.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        departmentButton = new javax.swing.JButton();
        positionButton = new javax.swing.JButton();
        employeeManagementButton = new javax.swing.JButton();
        applicantButton = new javax.swing.JButton();
        attendanceButton = new javax.swing.JButton();
        leaveManagementButton = new javax.swing.JButton();
        schedueleButton = new javax.swing.JButton();
        salaryButton = new javax.swing.JButton();
        logoutPanel = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(31, 41, 55));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 494));

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.GridLayout(9, 1));

        homeButton.setBackground(new java.awt.Color(31, 41, 55));
        homeButton.setFocusPainted(false);
        homeButton.setOpaque(true);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel7.add(homeButton);

        departmentButton.setBackground(new java.awt.Color(31, 41, 55));
        departmentButton.setFocusPainted(false);
        departmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentButtonActionPerformed(evt);
            }
        });
        jPanel7.add(departmentButton);

        positionButton.setBackground(new java.awt.Color(31, 41, 55));
        positionButton.setFocusPainted(false);
        positionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionButtonActionPerformed(evt);
            }
        });
        jPanel7.add(positionButton);

        employeeManagementButton.setBackground(new java.awt.Color(31, 41, 55));
        employeeManagementButton.setFocusPainted(false);
        employeeManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeManagementButtonActionPerformed(evt);
            }
        });
        jPanel7.add(employeeManagementButton);

        applicantButton.setBackground(new java.awt.Color(31, 41, 55));
        applicantButton.setFocusPainted(false);
        applicantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicantButtonActionPerformed(evt);
            }
        });
        jPanel7.add(applicantButton);

        attendanceButton.setBackground(new java.awt.Color(31, 41, 55));
        attendanceButton.setFocusPainted(false);
        attendanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceButtonActionPerformed(evt);
            }
        });
        jPanel7.add(attendanceButton);

        leaveManagementButton.setBackground(new java.awt.Color(31, 41, 55));
        leaveManagementButton.setFocusPainted(false);
        leaveManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveManagementButtonActionPerformed(evt);
            }
        });
        jPanel7.add(leaveManagementButton);

        schedueleButton.setBackground(new java.awt.Color(31, 41, 55));
        schedueleButton.setFocusPainted(false);
        schedueleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedueleButtonActionPerformed(evt);
            }
        });
        jPanel7.add(schedueleButton);

        salaryButton.setBackground(new java.awt.Color(31, 41, 55));
        salaryButton.setFocusPainted(false);
        salaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryButtonActionPerformed(evt);
            }
        });
        jPanel7.add(salaryButton);

        logoutPanel.setOpaque(false);

        logoutButton.setBackground(new java.awt.Color(255, 102, 0));
        logoutButton.setFocusPainted(false);
        logoutButton.setFocusable(false);

        javax.swing.GroupLayout logoutPanelLayout = new javax.swing.GroupLayout(logoutPanel);
        logoutPanel.setLayout(logoutPanelLayout);
        logoutPanelLayout.setHorizontalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoutPanelLayout.setVerticalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(31, 41, 55));

        logoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(590, 60));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Employee Management System");

        jButton8.setBackground(new java.awt.Color(255, 102, 0));
        jButton8.setFocusable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(585, 45));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Dashboard");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(424, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(14, 14, 14))
        );

        jPanel5.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        toggleButton();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
//        jPanel5.removeAll();
//        Home home = new Home();
//        jPanel5.add(home);
//        SwingUtilities.updateComponentTreeUI(jPanel5);

        jPanel5.removeAll();
        HomePanel home = new HomePanel();
        jPanel5.add(home);
        SwingUtilities.updateComponentTreeUI(jPanel5);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void departmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentButtonActionPerformed
        jPanel5.removeAll();
        DepartmentPanel department = new DepartmentPanel();
        jPanel5.add(department);
        SwingUtilities.updateComponentTreeUI(jPanel5);
    }//GEN-LAST:event_departmentButtonActionPerformed

    private void positionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionButtonActionPerformed
        jPanel5.removeAll();
        PositionPanel position = new PositionPanel();
        jPanel5.add(position);
        SwingUtilities.updateComponentTreeUI(jPanel5);
    }//GEN-LAST:event_positionButtonActionPerformed

    private void employeeManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeManagementButtonActionPerformed
        jPanel5.removeAll();
        EmployeePanel employee = new EmployeePanel();
        jPanel5.add(employee);
        SwingUtilities.updateComponentTreeUI(jPanel5);
    }//GEN-LAST:event_employeeManagementButtonActionPerformed

    private void applicantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicantButtonActionPerformed
        jPanel5.removeAll();
        ApplicantPanel applicant = new ApplicantPanel();
        jPanel5.add(applicant);
        SwingUtilities.updateComponentTreeUI(jPanel5);
    }//GEN-LAST:event_applicantButtonActionPerformed

    private void attendanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceButtonActionPerformed
        jPanel5.removeAll();
        AttendancePanel attendance = new AttendancePanel();
        jPanel5.add(attendance);
        SwingUtilities.updateComponentTreeUI(jPanel5);
    }//GEN-LAST:event_attendanceButtonActionPerformed

    private void leaveManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveManagementButtonActionPerformed
        jPanel5.removeAll();
        LeavePanel leave = new LeavePanel();
        jPanel5.add(leave);
        SwingUtilities.updateComponentTreeUI(jPanel5);
    }//GEN-LAST:event_leaveManagementButtonActionPerformed

    private void schedueleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedueleButtonActionPerformed
        jPanel5.removeAll();
        ScheduelePanel scheduele = new ScheduelePanel();
        jPanel5.add(scheduele);
        SwingUtilities.updateComponentTreeUI(jPanel5);
    }//GEN-LAST:event_schedueleButtonActionPerformed

    private void salaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryButtonActionPerformed
        jPanel5.removeAll();
        SalaryPanel salary = new SalaryPanel();
        jPanel5.add(salary);
        SwingUtilities.updateComponentTreeUI(jPanel5);
    }//GEN-LAST:event_salaryButtonActionPerformed

    private void toggleButton() {
        if (isCollapsed) {
            // Expand the sidebar
            jPanel1.setPreferredSize(new Dimension(EXPANDED_WIDTH, getHeight()));
        } else {
            // Collapse the sidebar
            jPanel1.setPreferredSize(new Dimension(COLLAPSED_WIDTH, getHeight()));
        }

        // Toggle the collapsed state
        isCollapsed = !isCollapsed;

        // Refresh layout and repaint
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //FlatMacLightLaf.setup();
        FlatMacDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applicantButton;
    private javax.swing.JButton attendanceButton;
    private javax.swing.JButton departmentButton;
    private javax.swing.JButton employeeManagementButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton leaveManagementButton;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JButton positionButton;
    private javax.swing.JButton salaryButton;
    private javax.swing.JButton schedueleButton;
    // End of variables declaration//GEN-END:variables
}
