/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.panels;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import gui.dialogs.ApplicantForm;
import gui.dialogs.MarkInForm;
import gui.dialogs.MarkOutForm;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.SystemManager;

/**
 *
 * @author senad
 */
public class AttendancePanel extends javax.swing.JPanel {

    /**
     * Creates new form AttendancePanel
     */
    private FlatSVGIcon searchIcon;

    public AttendancePanel() {
        initComponents();
        initUI();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        markInButton = new javax.swing.JButton();
        markOutButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        attendanceTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextField2.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2.setToolTipText("test");
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jTextField2.setName("t"); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(51, 51, 51));
        searchButton.setBorderPainted(false);
        searchButton.setFocusPainted(false);

        markInButton.setBackground(new java.awt.Color(0, 153, 51));
        markInButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        markInButton.setForeground(new java.awt.Color(255, 255, 255));
        markInButton.setText("Mark In");
        markInButton.setBorderPainted(false);
        markInButton.setFocusPainted(false);
        markInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markInButtonActionPerformed(evt);
            }
        });

        markOutButton.setBackground(new java.awt.Color(204, 153, 0));
        markOutButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        markOutButton.setForeground(new java.awt.Color(255, 255, 255));
        markOutButton.setText("Mark Out");
        markOutButton.setBorderPainted(false);
        markOutButton.setFocusPainted(false);
        markOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markOutButtonActionPerformed(evt);
            }
        });

        attendanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "attendance_id", "employee_id", "fname", "lname", "nic", "year", "month", "in", "out"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(attendanceTable);

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(84, 84, 84));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Attendance Management");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(markInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markOutButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(markInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(markOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addGap(39, 39, 39))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void markInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markInButtonActionPerformed
        MarkInForm df = new MarkInForm(null, true);
        df.setVisible(true);
        loadTable();
    }//GEN-LAST:event_markInButtonActionPerformed

    private void markOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markOutButtonActionPerformed
        MarkOutForm df = new MarkOutForm(null, true);
        df.setVisible(true);
        loadTable();
    }//GEN-LAST:event_markOutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable attendanceTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton markInButton;
    private javax.swing.JButton markOutButton;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables

    private void initUI() {
        searchIcon = new FlatSVGIcon("resources//search-icon.svg", 20, 20);
        searchButton.setIcon(searchIcon);
    }

    private void loadTable() {

        // 1. Get today's date
        LocalDate today = LocalDate.now();

        // 2. Define the required format (yyyy-MM-dd)
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

        // 3. Format today's date into the required String format
        String todayDateString = today.format(formatter);
        
        try {
            loadAttendanceDataToTable(SystemManager.getAttendanceManager().getAttendanceByDate(todayDateString));
        } catch (Exception ex) {
//            System.out.println("Error in form: " + ex.getMessage());
            ex.printStackTrace();
        }
    }

    private void loadAttendanceDataToTable(ResultSet rs) {
        try {
            // 1. Cast the table's model and clear previous data
            // NOTE: Replace 'departmentTable' with your actual JTable component name (e.g., 'attendanceTable')
            DefaultTableModel model = (DefaultTableModel) attendanceTable.getModel();
            model.setRowCount(0); // Clear existing rows

            // 2. Iterate through the ResultSet
            while (rs.next()) {
                // Create a Vector to hold the data for the current row
                Vector<Object> rowData = new Vector<>();

                // Fetch and add data using the column aliases from your SELECT query:
                // The ResultSet stores data based on column aliases, so use them here.
                rowData.add(rs.getInt("attendance_id"));
                rowData.add(rs.getInt("employee_id"));
                rowData.add(rs.getString("fname"));
                rowData.add(rs.getString("lname"));
                rowData.add(rs.getString("nic"));
                rowData.add(rs.getString("year"));
                rowData.add(rs.getString("month"));
                // Use getString() or getTimestamp() for 'in' and 'out' times
                rowData.add(rs.getString("in"));
                rowData.add(rs.getString("out"));

                // Add the calculated duration (optional, for demonstration)
                // If you want to calculate duration, you'd need the Timestamp objects:
                // long duration = rs.getTimestamp("out").getTime() - rs.getTimestamp("in").getTime();
                // rowData.add(Duration.ofMillis(duration).toMinutes() + " min");
                model.addRow(rowData);
            }

            // 3. Center-align cell contents (NOTE: Replace 'departmentTable' with 'attendanceTable')
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);

            for (int i = 0; i < attendanceTable.getColumnCount(); i++) {
                attendanceTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }

        } catch (SQLException e) {
            // Handle database access errors
            e.printStackTrace();
        }
    }

}
