/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.panels;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import gui.dialogs.LeaveForm;
import gui.dialogs.MarkOutForm;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.Vector;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.SystemManager;
import util.Utility;

/**
 *
 * @author senad
 */
public class LeavePanel extends javax.swing.JPanel {

    /**
     * Creates new form LeavePanel
     */
    private FlatSVGIcon searchIcon;

    public LeavePanel() {
        initComponents();
        initUI();
        loadTable();
        
                Utility.customizeTable(leavesTable);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        searchButton = new javax.swing.JButton();
        leaveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        leavesTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setToolTipText("test");
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jTextField1.setName("t"); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Status" }));

        searchButton.setBackground(new java.awt.Color(51, 51, 51));
        searchButton.setBorderPainted(false);
        searchButton.setFocusPainted(false);

        leaveButton.setBackground(new java.awt.Color(102, 51, 255));
        leaveButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        leaveButton.setForeground(new java.awt.Color(255, 255, 255));
        leaveButton.setText("Add a Leave");
        leaveButton.setBorderPainted(false);
        leaveButton.setFocusPainted(false);
        leaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveButtonActionPerformed(evt);
            }
        });

        leavesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "leave_id", "employee_id", "fname", "lname", "nic", "date", "reason"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(leavesTable);

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(84, 84, 84));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Leave Management");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        editButton.setBackground(new java.awt.Color(0, 204, 51));
        editButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setBorderPainted(false);
        editButton.setFocusPainted(false);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        FlatSVGIcon editIcon = new FlatSVGIcon("resources//edit2.svg", 20, 20);
        editButton.setIcon(editIcon);

        deleteButton.setBackground(new java.awt.Color(51, 51, 51));
        deleteButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setBorderPainted(false);
        deleteButton.setFocusPainted(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        FlatSVGIcon deleteIcon = new FlatSVGIcon("resources//delete2.svg", 18, 18);
        deleteButton.setIcon(deleteIcon);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(leaveButton)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(leaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void leaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveButtonActionPerformed
        LeaveForm df = new LeaveForm(null, true);
        df.setVisible(true);
        loadTable();
    }//GEN-LAST:event_leaveButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton leaveButton;
    private javax.swing.JTable leavesTable;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables

    private void initUI() {
        searchIcon = new FlatSVGIcon("resources//search-icon.svg", 20, 20);
        searchButton.setIcon(searchIcon);
    }

    private void loadLeaveDataToTable(ResultSet rs) {
        try {
            // 1. Cast the table's model and clear previous data
            // NOTE: Replace 'departmentTable' with your actual JTable component name (e.g., 'leavesTable')
            DefaultTableModel model = (DefaultTableModel) leavesTable.getModel();
            model.setRowCount(0); // Clear existing rows

            // 2. Iterate through the ResultSet
            while (rs.next()) {
                // Create a Vector to hold the data for the current row. 
                // Using Object here is safer than String, though String works if all data is converted.
                Vector<Object> rowData = new Vector<>();

                // Fetch data using the 7 column aliases from the 'searchLeaves' SELECT query:
                // l.id AS leave_id
                rowData.add(rs.getInt("leave_id"));

                // l.employee_id
                rowData.add(rs.getInt("employee_id"));

                // e.fname
                rowData.add(rs.getString("fname"));

                // e.lname
                rowData.add(rs.getString("lname"));

                // e.nic
                rowData.add(rs.getString("nic"));

                // l.date
                rowData.add(rs.getString("date")); // Date can be fetched as String

                // l.reason
                rowData.add(rs.getString("reason"));

                model.addRow(rowData);
            }

            // 3. Center-align cell contents (NOTE: Replace 'departmentTable' with 'leavesTable')
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);

            for (int i = 0; i < leavesTable.getColumnCount(); i++) {
                leavesTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }

        } catch (SQLException e) {
            // Handle database access errors
            e.printStackTrace();
        }
    }

    private void loadTable() {
        // Assuming this code resides in a class that has access to loadLeaveDataToTable method.

// 1. Get the current date
        LocalDate today = LocalDate.now();

// 2. Define a formatter to get the full month name (e.g., "November")
// MMMM represents the full month name. Using Locale.ENGLISH ensures it matches 
// the validation in your searchLeaves method.
        DateTimeFormatter monthFormatter = DateTimeFormatter.ofPattern("MMMM", Locale.ENGLISH);

// 3. Format the date to get the month name
        String currentMonthName = today.format(monthFormatter); // Example result: "November"

        try {
            // 4. Call the searchLeaves method with the current month's name
            ResultSet leaveResultSet = SystemManager.getLeaveManager().searchLeaves(currentMonthName);

            // 5. Pass the resulting ResultSet to the table loading method
            loadLeaveDataToTable(leaveResultSet);

        } catch (Exception e) {
            // Handle the Exceptions (NullPointerException, IllegalArgumentException, SQLException) 
            // that the searchLeaves method might throw.
            System.err.println("Error loading leave data: " + e.getMessage());
            // Optionally show a JOptionPane message to the user
        }
    }

}
