/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.panels;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import gui.dialogs.SalaryProcessForm;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.SystemManager;

/**
 *
 * @author senad
 */
public class SalaryPanel extends javax.swing.JPanel {

    /**
     * Creates new form SalarayPanel
     */
    private FlatSVGIcon searchIcon;

    public SalaryPanel() {
        initComponents();
        initUI();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        salaryButton = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        salaryTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jComboBox2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Status" }));

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        searchButton.setBackground(new java.awt.Color(51, 51, 51));
        searchButton.setBorderPainted(false);
        searchButton.setFocusPainted(false);

        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setToolTipText("test");
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jTextField1.setName("t"); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        salaryButton.setBackground(new java.awt.Color(102, 51, 255));
        salaryButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        salaryButton.setForeground(new java.awt.Color(255, 255, 255));
        salaryButton.setText("Add a Salary payment");
        salaryButton.setBorderPainted(false);
        salaryButton.setFocusPainted(false);
        salaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryButtonActionPerformed(evt);
            }
        });

        jComboBox3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Status" }));

        jTextField2.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2.setToolTipText("test");
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jTextField2.setName("t"); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        salaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "salary_id", "year", "month", "employee_id", "fname", "lname", "nic", "gross_amount", "deductions", "paid_amount", "created_at"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(salaryTable);

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(84, 84, 84));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Salary Management");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(salaryButton)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(salaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void salaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryButtonActionPerformed
        SalaryProcessForm df = new SalaryProcessForm(null, true);
        df.setVisible(true);
    }//GEN-LAST:event_salaryButtonActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton salaryButton;
    private javax.swing.JTable salaryTable;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables

    private void initUI() {
        searchIcon = new FlatSVGIcon("resources//search-icon.svg", 20, 20);
        searchButton.setIcon(searchIcon);
    }

    private void loadSalaryDataToTable(ResultSet rs) {
        try {
            // 1. Cast the table's model and clear previous data
            // NOTE: Replace 'departmentTable' with your actual JTable component name (e.g., 'salaryTable')
            DefaultTableModel model = (DefaultTableModel) salaryTable.getModel();
            model.setRowCount(0); // Clear existing rows

            // 2. Iterate through the ResultSet
            while (rs.next()) {
                // Create a Vector to hold the data for the current row.
                Vector<Object> rowData = new Vector<>();

                // Fetch data using the 11 column aliases from the 'search' SELECT query:
                // s.id AS salary_id
                rowData.add(rs.getInt("salary_id"));

                // s.year
                rowData.add(rs.getInt("year"));

                // s.month
                rowData.add(rs.getString("month"));

                // s.employee_id
                rowData.add(rs.getInt("employee_id"));

                // e.fname
                rowData.add(rs.getString("fname"));

                // e.lname
                rowData.add(rs.getString("lname"));

                // e.nic
                rowData.add(rs.getString("nic"));

                // s.gross_amount (Use getDouble for currency/amount)
                rowData.add(rs.getDouble("gross_amount"));

                // s.deductions (Use getDouble for currency/amount)
                rowData.add(rs.getDouble("deductions"));

                // paid_amount (This is the calculated net salary)
                rowData.add(rs.getDouble("paid_amount"));

                // s.created_at
                rowData.add(rs.getString("created_at"));

                model.addRow(rowData);
            }

            // 3. Center-align cell contents (NOTE: Replace 'departmentTable' with 'salaryTable')
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);

            for (int i = 0; i < salaryTable.getColumnCount(); i++) {
                salaryTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }

        } catch (SQLException e) {
            // Handle database access errors
            e.printStackTrace();
        }
    }

    private void loadTable() {
        // 1. Get the current month name
        LocalDate today = LocalDate.now();
        DateTimeFormatter monthFormatter = DateTimeFormatter.ofPattern("MMMM", Locale.ENGLISH);
        String currentMonthName = today.format(monthFormatter);

        ResultSet salaryResultSet = null;
        try {
            // 2. Call the search method using the current month name
            // Assuming your 'search' method belongs to the SalaryManager class.
            salaryResultSet = SystemManager.getSalaryManager().search(currentMonthName);

            // 3. Call the table loading method
            // NOTE: Replace this with the actual name of your table loading method.
            // Based on your previous request, I'll use loadSalaryDataToTable.
            loadSalaryDataToTable(salaryResultSet);

        } catch (NullPointerException | IllegalArgumentException e) {
            // Handles validation exceptions thrown by the search method (e.g., if month is invalid)
            JOptionPane.showMessageDialog(
                    this,
                    "Validation Error: " + e.getMessage(),
                    "Data Load Error",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (Exception e) {
            // Handles SQLExceptions or other general exceptions
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                    this,
                    "An error occurred while loading salary data: " + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
}
