/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.panels;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import gui.dialogs.SheduleForm;
import java.util.Vector;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.SystemManager;
import util.Utility;

/**
 *
 * @author senad
 */
public class ScheduelePanel extends javax.swing.JPanel {

    /**
     * Creates new form ScheduelePanel
     */
    public ScheduelePanel() {
        initComponents();
        loadTable();
        
        Utility.customizeTable(scheduleTable);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scheduleTable = new javax.swing.JTable();
        schedueleButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        scheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "  schedule_id", "  date", "  time", "  applicant_id", "  fname", "  lname", "  nic", "  email", "  mobile", "  position_id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(scheduleTable);

        schedueleButton.setBackground(new java.awt.Color(102, 51, 255));
        schedueleButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        schedueleButton.setForeground(new java.awt.Color(255, 255, 255));
        schedueleButton.setText("Add a Scheduele");
        schedueleButton.setBorderPainted(false);
        schedueleButton.setFocusPainted(false);
        schedueleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedueleButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(84, 84, 84));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Scheduele Management");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        editButton.setBackground(new java.awt.Color(0, 204, 51));
        editButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setBorderPainted(false);
        editButton.setFocusPainted(false);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        FlatSVGIcon editIcon = new FlatSVGIcon("resources//edit2.svg", 20, 20);
        editButton.setIcon(editIcon);

        deleteButton.setBackground(new java.awt.Color(51, 51, 51));
        deleteButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setBorderPainted(false);
        deleteButton.setFocusPainted(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        FlatSVGIcon deleteIcon = new FlatSVGIcon("resources//delete2.svg", 18, 18);
        deleteButton.setIcon(deleteIcon);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(schedueleButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(schedueleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void schedueleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedueleButtonActionPerformed
        SheduleForm df = new SheduleForm(null, true);
        df.setVisible(true);
        loadTable();
    }//GEN-LAST:event_schedueleButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton schedueleButton;
    private javax.swing.JTable scheduleTable;
    // End of variables declaration//GEN-END:variables

    private void loadScheduleDataToTable(ResultSet rs) {
        try {

            // 1. Get the model and clear existing rows
            DefaultTableModel model = (DefaultTableModel) scheduleTable.getModel();
            model.setRowCount(0); // Clear existing rows

            // 2. Iterate through the ResultSet
            while (rs.next()) {
                // Create a Vector to hold the data for the current row.
                Vector<Object> rowData = new Vector<>();

                // Fetch data using the 10 column aliases from the SELECT query:
                // s.id AS schedule_id
                rowData.add(rs.getInt("schedule_id"));

                // s.date (Assuming yyyy-MM-dd format)
                rowData.add(rs.getString("date"));

                // s.time (Assuming HH:mm format)
                rowData.add(rs.getString("time"));

                // a.id AS applicant_id
                rowData.add(rs.getInt("applicant_id"));

                // a.fname
                rowData.add(rs.getString("fname"));

                // a.lname
                rowData.add(rs.getString("lname"));

                // a.nic
                rowData.add(rs.getString("nic"));

                // a.email
                rowData.add(rs.getString("email"));

                // a.mobile
                rowData.add(rs.getString("mobile"));

                // a.position_id
                rowData.add(rs.getInt("position_id"));

                model.addRow(rowData);
            }

            // 3. Center-align cell contents
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);

            for (int i = 0; i < scheduleTable.getColumnCount(); i++) {
                scheduleTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }

        } catch (SQLException e) {
            // Handle database access errors
            e.printStackTrace();
            // Optionally, display an error message to the user
        }
    }

    private void loadTable() {
        ResultSet scheduleResultSet = null;
        try {
            // Fetch the ResultSet containing all schedule data
            // Assuming the ScheduleManager is accessed via SystemManager
            scheduleResultSet = SystemManager.getScheduleManager().getAllSchedules();

            // Pass the fetched ResultSet to the data loading method
            loadScheduleDataToTable(scheduleResultSet);

        } catch (Exception e) {
            // Handle potential exceptions from getAllSchedules (e.g., database connection issues)
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                    null,
                    "An error occurred while fetching schedule data: " + e.getMessage(),
                    "System Error",
                    JOptionPane.ERROR_MESSAGE
            );
        } 
    }

}
