/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.dialogs;

import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.SystemManager;

/**
 *
 * @author senad
 */
public class SalaryProcessForm extends javax.swing.JDialog {

    /**
     * Creates new form departmentForm
     */
    public SalaryProcessForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        netSalaryField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        paySalaryButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        yearField = new javax.swing.JFormattedTextField();
        monthComboBox = new javax.swing.JComboBox<>();
        nicField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        grossSalaryField = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        deductionField = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        netSalaryField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create a department");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(60, 100));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cancelButton.setBackground(new java.awt.Color(0, 0, 0));
        cancelButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.setBorderPainted(false);
        cancelButton.setFocusPainted(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        paySalaryButton.setBackground(new java.awt.Color(102, 51, 255));
        paySalaryButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        paySalaryButton.setForeground(new java.awt.Color(255, 255, 255));
        paySalaryButton.setText("Pay Salary");
        paySalaryButton.setBorderPainted(false);
        paySalaryButton.setFocusPainted(false);
        paySalaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paySalaryButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(58, 58, 58));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Add New Department");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator1.setForeground(new java.awt.Color(219, 219, 219));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(76, 76, 76));
        jLabel1.setText("Employee NIC *");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(2, 2, 15, 0));

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(76, 76, 76));
        jLabel8.setText("Year *");
        jPanel3.add(jLabel8);

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(76, 76, 76));
        jLabel3.setText("Month *");
        jPanel3.add(jLabel3);

        yearField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        yearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearFieldActionPerformed(evt);
            }
        });
        jPanel3.add(yearField);

        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jPanel3.add(monthComboBox);

        jLabel11.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(76, 76, 76));
        jLabel11.setText("Gross Amount *");

        grossSalaryField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        grossSalaryField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                grossSalaryFieldKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(76, 76, 76));
        jLabel12.setText("Deductions *");

        deductionField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        deductionField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                deductionFieldKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(76, 76, 76));
        jLabel13.setText("New Salaray (Calculated)*");

        netSalaryField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        netSalaryField.setText("0.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nicField)
                    .addComponent(grossSalaryField)
                    .addComponent(deductionField)
                    .addComponent(netSalaryField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nicField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grossSalaryField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deductionField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(netSalaryField, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(234, Short.MAX_VALUE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(paySalaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paySalaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void paySalaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paySalaryButtonActionPerformed
        // 1. Retrieve and Validate Text Fields
        String year;
        String monthName;
        String nic;
        double grossAmount;
        double deductions;

        try {
            // YEAR Validation
            year = yearField.getText().trim();
            if (year.isEmpty()) {
                throw new Exception("Year field cannot be empty.");
            }

            // MONTH Validation (assuming JComboBox is populated with full month names)
            monthName = (String) monthComboBox.getSelectedItem();
            if (monthName == null || monthName.trim().isEmpty()) {
                throw new Exception("Please select a month.");
            }

            // NIC Validation
            nic = nicField.getText().trim();
            if (nic.isEmpty()) {
                throw new Exception("NIC field cannot be empty.");
            }

            // GROSS AMOUNT Validation and Parsing
            grossAmount = parseAmountField(grossSalaryField, "Gross Salary");

            // DEDUCTIONS Validation and Parsing
            deductions = parseAmountField(deductionField, "Deductions");

        } catch (Exception e) {
            // Display validation error to the user
            JOptionPane.showMessageDialog(
                    this,
                    "Validation Failed: " + e.getMessage(),
                    "Input Error",
                    JOptionPane.WARNING_MESSAGE
            );
            return; // Stop execution
        }

        // 2. Call the Manager Method
        try {
            String result = SystemManager.getSalaryManager().createSalaryRecord(
                    year,
                    monthName,
                    nic,
                    grossAmount,
                    deductions
            );

            // 3. Handle the Result String
            String message;
            int messageType;

            switch (result) {
                case "success":
                    message = "Salary record successfully created and paid.";
                    messageType = JOptionPane.INFORMATION_MESSAGE;
                    this.dispose();
                    break;
                case "employee_not_found":
                    message = "Error: Employee with NIC '" + nic + "' was not found.";
                    messageType = JOptionPane.ERROR_MESSAGE;
                    break;
                case "salary_record_already_exists":
                    message = "Error: Salary for " + monthName + " " + year + " has already been paid to this employee.";
                    messageType = JOptionPane.ERROR_MESSAGE;
                    break;
                case "cannot_pay_salary_due_to_low_attendance_and_leave_count":
                    message = "Payment denied: Employee does not meet the minimum attendance/leave requirement (20 days).";
                    messageType = JOptionPane.ERROR_MESSAGE;
                    break;
                case "Failed":
                    message = "Operation failed. Database insertion returned 0 rows affected.";
                    messageType = JOptionPane.ERROR_MESSAGE;
                    break;
                default:
                    message = "Unknown error occurred.";
                    messageType = JOptionPane.ERROR_MESSAGE;
                    break;
            }

            JOptionPane.showMessageDialog(this, message, "Salary Payment", messageType);

        } catch (Exception e) {
            // Catch exceptions thrown by the manager method itself (e.g., database connection issues, 
            // internal validation in the manager method, etc.)
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                    this,
                    "A system error occurred during salary processing: " + e.getMessage(),
                    "System Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_paySalaryButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void grossSalaryFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_grossSalaryFieldKeyReleased
        calculateNetSalary();
    }//GEN-LAST:event_grossSalaryFieldKeyReleased

    private void deductionFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deductionFieldKeyReleased
        calculateNetSalary();
    }//GEN-LAST:event_deductionFieldKeyReleased

    private void yearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaryProcessForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaryProcessForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaryProcessForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaryProcessForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SalaryProcessForm dialog = new SalaryProcessForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JFormattedTextField deductionField;
    private javax.swing.JFormattedTextField grossSalaryField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> monthComboBox;
    private javax.swing.JFormattedTextField netSalaryField;
    private javax.swing.JTextField nicField;
    private javax.swing.JButton paySalaryButton;
    private javax.swing.JFormattedTextField yearField;
    // End of variables declaration//GEN-END:variables

    /**
     * Helper method to safely retrieve a numeric value from a JTextField.
     * Returns 0.0 if the field is empty or contains non-numeric characters.
     */
    private double getNumericValue(JTextField field) {
        String text = field.getText().trim();
        if (text.isEmpty()) {
            return 0.0;
        }
        try {
            // Use Double.parseDouble to handle decimal values
            return Double.parseDouble(text);
        } catch (NumberFormatException e) {
            // Optionally, log the error or show a warning to the user 
            // about invalid characters.
            return 0.0;
        }
    }

    /**
     * Calculates the Net Salary and updates the Net Salary field.
     */
    private void calculateNetSalary() {
        // 1. Get safe numeric values from the two source fields
        double grossSalary = getNumericValue(grossSalaryField);
        double deductions = getNumericValue(deductionField);

        // 2. Perform the calculation: netsalary = grosssalary - deductions
        double netSalary = grossSalary - deductions;

        // 3. Update the netSalaryField with the result (formatted to two decimal places)
        netSalaryField.setText(String.format("%.2f", netSalary));
    }

    /**
     * Helper method to safely parse a double from a text field. Throws an
     * exception if the format is invalid or if the field is empty/null.
     */
    private double parseAmountField(JFormattedTextField field, String fieldName) throws Exception {
        String text = field.getText();
        if (text == null || text.trim().isEmpty()) {
            throw new Exception(fieldName + " cannot be empty.");
        }
        try {
            return Double.parseDouble(text.trim());
        } catch (NumberFormatException e) {
            throw new Exception("Invalid format for " + fieldName + ". Please enter a valid number.");
        }
    }

}
